Dark mode
vitaliyoliynykk/notes-app pull request #14
Opened 2020-09-14 14:17 UTC by leshihak

2020-09-15 17:33 UTC, vitaliyoliynykk requested changes

2020-09-15 17:33 UTC, vitaliyoliynykk commented on src/components/NoteItem/NoteItem.scss
> +.container-note--dark {
Why do you copy such properties as paddins, cursor, transition etc. When you only need to change color?

2020-09-15 17:33 UTC, vitaliyoliynykk commented on src/components/NoteItem/NoteItem.tsx
> +    const removeModalTitle = 'Do you really want to remove a Note?';
Move this to separate file NoteItem.constants

2020-09-15 17:33 UTC, vitaliyoliynykk commented on src/components/NoteItem/NoteItem.tsx
> +    let noteClass = 'container-note';
it looks like spaghetti code, consider using classname, or at least move it to separate function

2020-09-15 17:33 UTC, vitaliyoliynykk commented on src/components/NoteItem/NoteItem.tsx
> +    darkMode: boolean;
consider rename it "isDarkMode"

2020-09-15 17:33 UTC, vitaliyoliynykk commented on src/components/NoteItemsList/NoteItemsList.tsx
> +    darkMode: boolean;
rename to isDarkMode in the whole project

2020-09-15 17:33 UTC, vitaliyoliynykk commented on src/components/RemoveModal/RemoveModal.scss
> +    &--btn {
'--' is modifier, not element. Lets use official methodology http://getbem.com/

2020-09-15 17:33 UTC, vitaliyoliynykk commented on src/components/RemoveModal/RemoveModal.scss
> +.container-modal__block--dark {
here you use "--dark" as modifier, and in code above as element. This is inconsistent

2020-09-15 17:33 UTC, vitaliyoliynykk commented on src/components/TextEditor/TextEditor.scss
> +        &_description {
you dont need this

2020-09-16 20:23 UTC, leshihak commented
And watch Notes component for removing notes (bug)

2020-09-17 13:11 UTC, vitaliyoliynykk requested changes

2020-09-17 13:11 UTC, vitaliyoliynykk commented on src/components/Loader/Loader.scss
> +    position: absolute;
you shouldnt set absolute position to component. Instead wrap it into div wherever you want to use it, and set absolute position to div

2020-09-17 13:11 UTC, vitaliyoliynykk commented on src/containers/Notes/Notes.tsx
>                  }
add "catch" block to set loading to false if there is an error

2020-09-17 19:09 UTC, merged